name: flutter_proyecto_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.1.0 # Asegúrate de que esta dependencia esté en tu pubspec.yaml
  appwrite: ^11.0.1
  url_launcher: ^6.2.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/banner1.jpg
    - assets/banner2.jpg
    - assets/banner3.jpg
    - assets/banner4.jpg
    - assets/banner5.jpg
    # Si tienes otras imágenes de productos en una subcarpeta 'assets/products/', añádelas aquí:
    # - assets/products/